version: "3.9"

services:
  goshne:
    container_name: goshne_app
    image: ahbanavi/goshne:latest
    command: ["python", "main.py"]
    volumes:
      - ./storage:/usr/src/app/storage:rw
      - ./config:/usr/src/app/config:ro